services:
  frontend:
    image: frontend-semana-3
    ports:
      - "8080:80"
    volumes:
      - ./frontend/certificados/:/etc/nginx/ssl
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    networks:
      - application

  backend:
    image: api-semana-3
    ports:
      - "5000:5000"
    environment:
      APP_DEBUG: None
      APP_PORT: 5000
      APP_HOST: 0.0.0.0
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      IMAGE_MICROSERVICE_HOST: localhost
      IMAGE_MICROSERVICE_PORT: 3001
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    networks:
      - data
      - application

  image-microservice:
    image: image-microservice-semana3
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    networks:
      - redmicroservicio

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    volumes:
      - mng:/data/db
    networks:
      - data

  redis:
    image: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2GiB
        reservations:
          cpus: '0.5'
          memory: 1GiB
    volumes:
      - rd:/data
    networks:
      - data

volumes:
  mng: {}
  rd: {}

networks:
  application:
    driver: overlay
  data:
    driver: overlay
  redmicroservicio:
    driver: overlay
